development:
  adapter: mysql
  database: the_incentosaur_development
  username: root
  password: 
  host: localhost
test:
  adapter: mysql
  database: the_incentosaur_test
  username: root
  password: 
  host: localhost